### ISSUE TITLE
Rotating screen discards unsaved text

### ISSUE THREAD

**Issue by cleeff** [alisonthemonster/GratitudeJournal#106]
Steps to reproduce.
- Write and save an entry for a day
- go back to menu and open again that day
- write some more text
- rotate the screen
- find that your additional text has been gone

I'm using Android 10, app 1.5.4.

**Comment by alisonthemonster** [comment]
Thank you so much for the report! Leaving it open until I get a moment to fix it or so someone else can take it on :)

**Comment by ch8n** [comment]
@alisonthemonster I would like to work on this, if this open for contribution, please assign it to me

**Comment by alisonthemonster** [comment]
Thank you!

**Comment by ch8n** [comment]
> Thank you!

hi @alisonthemonster I'm participating in Hacktober fest can you please mark this for a contribution. guide is below
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by alisonthemonster** [comment]
Done!

**Comment by ch8n** [comment]
> Done!

Hello @alisonthemonster 
I have created a PR #148 for this please do the code review, also when accepted please Mark it hacktoberfest accepted
