### ISSUE TITLE
Settings Icons are Pink

### ISSUE THREAD

**Issue by cypressious** [alisonthemonster/GratitudeJournal#118]
Running on Android 5.1 x86 emulator with Google APIs.

![grafik](https://user-images.githubusercontent.com/1191816/89279927-3f86a700-d648-11ea-9ce4-3ab950318b49.png)

**Comment by ch8n** [comment]
@alisonthemonster I would like to work on this, is this open for contribution?

**Comment by alisonthemonster** [comment]
Definitely open for contribution! :)

**Comment by ch8n** [comment]
@alisonthemonster @cypressious min supported API version is 23 which is Android 6, but the bug is reported for 5.1, is this still a valid bug?

**Comment by alisonthemonster** [comment]
Interesting! I do still see one pink icon running on API 23
<img width="330" alt="Screen Shot 2020-10-17 at 1 57 16 PM" src="https://user-images.githubusercontent.com/10744793/96353409-b09efd80-1080-11eb-9faf-e1c82a6feb86.png">

**Comment by ch8n** [comment]
@alisonthemonster  can you share the emulator specs?
I have tried several, but able to reproduce

[edit 1]: also I see share action missing 

Emulator : Pixel 2 API-23 : x86 Google API
Unable to reproduce
<img width="606" alt="Screenshot 2020-11-16 at 1 05 47 PM" src="https://user-images.githubusercontent.com/11576342/99224510-786c1580-280c-11eb-9f2d-f78b5254707b.png">

Emulator : Pixel 2 API-23 : arm-7a Google API
Unable to reproduce
<img width="606" alt="Screenshot 2020-11-16 at 12 58 03 PM" src="https://user-images.githubusercontent.com/11576342/99224040-92592880-280b-11eb-9bbb-2a4719cd2c4d.png">

**Comment by alisonthemonster** [comment]
Just had another report of this from a user with an HTC One X9 running on Noughat.

**Comment by alisonthemonster** [comment]
Also noticed this here on API 23 emulator.

<img width="353" alt="Screen Shot 2020-12-20 at 12 53 19 PM" src="https://user-images.githubusercontent.com/10744793/102724155-645f7c00-42c2-11eb-821d-8fe4a1320b84.png">
