### ISSUE TITLE
Update code to use new Activity Results API

### ISSUE THREAD

**Issue by alisonthemonster** [alisonthemonster/GratitudeJournal#127]
Updating the Fragment AndroidX dependency has made `startActivityForResult` deprecated and we should replace it with the new Activity Results API as described here: [https://developer.android.com/training/basics/intents/result](https://developer.android.com/training/basics/intents/result)

**Comment by ch8n** [comment]
hi @alisonthemonster I will like to work on this

**Comment by alisonthemonster** [comment]
@ch8n great! Let me know if you have any questions!

**Comment by ch8n** [comment]
hi @alisonthemonster please assign it to me, also I'm participating in the Hacktober fest can you please mark this for a contribution. guide is below
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by ch8n** [comment]
> @ch8n great! Let me know if you have any questions!

Hello @alisonthemonster 
I have created a PR #147  for this please, 
1. assign it to me, 
2. do the code review,
3. when accepted please Mark it hacktoberfest accepted
