### ISSUE TITLE
Background color of dialogs should match theme

### ISSUE THREAD

**Issue by peakvalleytech** [alisonthemonster/GratitudeJournal#189]
When dialogs are shown to the user, they are always the default, white. I suggest that they should be updated to be consistent with the current theme. The white is jarring especially when the theme is a dark theme and the time of day is night.

**Comment by alisonthemonster** [comment]
Good call out! Adding tags so we can get this done :)

**Comment by peakvalleytech** [comment]
@alisonthemonster Thanks, Alison. I'll get started asap.
