### ISSUE TITLE
Some icon colors don't match theme 

### ISSUE THREAD

**Issue by peakvalleytech** [alisonthemonster/GratitudeJournal#192]
![InkedScreenshot_1616612647_LI](https://user-images.githubusercontent.com/65185819/112369402-622e0480-8c99-11eb-9a19-ef7202f7329f.jpg)

**Comment by alisonthemonster** [comment]
Hi there! This is actually intentional! These are disabled settings so they appear differently.

**Comment by peakvalleytech** [comment]
> Hi there! This is actually intentional! These are disabled settings so they appear differently.

Right, I realized this, the day or day after, i posted. Finally got to closing this, but I guess you already did , so thanks!
