### ISSUE TITLE
Redundant use of shared prefrences

### ISSUE THREAD

**Issue by peakvalleytech** [alisonthemonster/GratitudeJournal#194]
PreferanceManager.getDefaultSharedPreferences is used in 9 files. 
Proposed solution: refactor as a kotlin extension in the main activity. 

So for example
  val sharedPrefs = PreferenceManager.getDefaultSharedPreferences(context)
  val showDayOfWeek = sharedPrefs?.getBoolean(DAY_OF_WEEK, false) ?: false

would turn into
 getBooleanPref
 getStringPref
 etc.

with those being extensions in ContainerActivity.

**Comment by alisonthemonster** [comment]
We've moved all of our settings logic into its own module and wrapped it, so now we're injecting the settings everywhere! Closing this since its no longer relevant.
