### ISSUE TITLE
Some inconsistent German strings

### ISSUE THREAD

**Issue by pal03377** [alisonthemonster/GratitudeJournal#198]
Some of the German translation used is written in an informal tone, and some is written formally.

(https://github.com/alisonthemonster/Presently/blob/develop/app/src/main/res/values-de/strings.xml)

For example, "Bist du sicher, dass du Einträge aus einer Datei importieren möchtest?" is informal (using du/dein/dir), but "Ihre Einträge werden in Dropbox gesichert" is formal (using Sie/Ihr/Ihre).

As a native speaker myself, I would suggest changing the translation strings to use the informal tone as it seems more fitting for something that personal like a gratitude app. Also, the main strings in the app (what_are_you_thankful_for, what_were_you_thankful_for, ...) already use informal tone anyways and the changes would only affect some strings in the settings this way.

I also found some strings that replaced the app name "Presently", but should not (like "Teile Derzeit" instead of "Teile Presently").

**Comment by alisonthemonster** [comment]
Thank you so much for taking the time to write this out and to make the corrections!

**Comment by pal03377** [comment]
Thank you for making this great free app!
