### ISSUE TITLE
Select theme screen is broken (edge to edge)

### ISSUE THREAD

**Issue by alisonthemonster** [alisonthemonster/GratitudeJournal#200]
Edge to edge is broken on a Pixel 4a. See the entry screen for a working example.

![device-2021-04-18-160221](https://user-images.githubusercontent.com/10744793/115163716-85ad5a80-a05f-11eb-983a-777d5da1d684.png)

**Comment by peakvalleytech** [comment]
@alisonthemonster Yes, it happens on my Pixel 5 too. I would be glad to help with this.

**Comment by peakvalleytech** [comment]
@alisonthemonster 
Ok, so I think i've fixed this issue, but before I send a PR, I would like to ask what is the use case for edge to edge in this app?

**Comment by alisonthemonster** [comment]
Edge to edge is a great UX improvement that allows us to expand the app window to extend across the entire screen.  To quote Chris Banes:
> By going edge-to-edge, apps will instead be laid out behind the system bars. This is to allow your app content to shine through to create a more immersive experience for your users.

It's especially prominent on devices that use gesture navigation. I'm reviewing your change now!
