### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by MohammedHsin** [alisonthemonster/GratitudeJournal#272]
Hi man. Your app is just great but I think it would be way better with the latest cutting-edge technologies. namely, compose! I would be honored to help you rewrite the whole UI using the world's most modern UI android kit ever created .. Jetpack Compose!  Tell me what you think :)

**Comment by alisonthemonster** [comment]
Hi! 
I've actually already started a rewrite in Compose. I'll let you know when its ready for contributions!
