### ISSUE TITLE
Add ability to share the app itself

### ISSUE THREAD

**Issue by alisonthemonster** [alisonthemonster/GratitudeJournal#92]
REQUIREMENTS
- [ ] A new item in settings for sharing Presently
- [ ] Opens the system share sheet and shares the play store listing 
- [ ] Title: "Share Presently"
- [ ] Description: "Enjoying Presently? Share the app with your friends and family
- [ ] Translated to all locales

**Comment by mrvivacious** [comment]
Hi! Presently is so dope. Thank you for the app and open-sourcing it!

I'm not taking this issue up soon but I'll leave this here:
[Documentation for system share sheet in Kotlin](https://developer.android.com/training/sharing/send#kotlin)

If I find time later and this feature hasn't been built, I'll see what I can do.
