### ISSUE TITLE
Regular backups

### ISSUE THREAD

**Issue by cleeff** [alisonthemonster/GratitudeJournal#94]
Great app! I was wondering how the backup process could be automated. I agree that this shouldn't be activated by default but it would be great to store an (encrypted?) version of the user input on Dropbox / Google Drive. Maybe similar to how WhatsApp does it.

I doesn't have to be implemented in the app itself, any solution would be fine to me.

**Comment by cleeff** [comment]
Ok I just saw the Pull request containing this feature xD please let me know when this is publicly available. I'd also be happy to beta test.

**Comment by alisonthemonster** [comment]
Hi there! Yes must have just missed me merging it! I'm hoping to get a beta build rolling out soon :)  You can sign up for our beta program here: https://forms.gle/LCk26Vrz2gkdrfZc7
