### ISSUE TITLE
Add "Select Language" Option to Settings

### ISSUE THREAD

**Issue by cor-bee** [alisonthemonster/GratitudeJournal#99]
Now, the app language is the same as the system language but it does not always work well.

For example, I have a system language set to English, but write on messenger and Presently mostly in Russian.

I would be grateful if you add the "Select Language" option to the Settings menu, so the app would be is in the same language of the content.

**Comment by alisonthemonster** [comment]
Hello!

This is a much requested feature and hopefully we can support it one day soon! Adding the enhancement tag in case contributors would like to take on this work :)
